version: "3.6"
services:
  function-registry-db:
    image: postgres:9.4
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=hermes
      - POSTGRES_PASSWORD=hermes
    networks:
      - hermes
    restart: "on-failure"

  function-registry-api:
    build:
      context: ./function-registry-api/packages/function-registry-api
      target: production
    ports:
      - "8080"
    networks:
      - hermes
    volumes:
      - ./logs/function-registry-api/:/app/logs
    restart: "on-failure"
    depends_on:
      - function-registry-db

  function-lifecycle-broker:
    image: redis
    ports:
      - "6379"
    networks:
      - hermes
    restart: "on-failure"

  function-orchestrator:
    build:
      context: ./function-orchestrator
      target: production
    environment:
      - DOCKER_BINARY_PATH=/usr/local/bin/docker
    ports:
      - 9090:3000
    networks:
      - hermes
    volumes:
      - ./logs/function-orchestrator/:/app/logs
      - ./results:/app/results
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "on-failure"
    depends_on:
      - function-lifecycle-broker
      - function-registry-api

volumes:
  pgdata:

networks:
  hermes:
    external: true
